project_id = ""
[api]
extra_search_path = ["public","extensions"]
max_rows = 1000
port = 54321
schemas = ["public","storage","graphql_public"]
[auth]
additional_redirect_urls = ["https://localhost:3000"]
enable_signup = true
jwt_expiry = 3600
site_url = "http://localhost:3000"
[auth.email]
double_confirm_changes = true
enable_confirmations = false
enable_signup = true
[auth.external.apple]
client_id = ""
enabled = false
redirect_uri = ""
secret = ""
url = ""
[db]
major_version = 15
port = 54322
[inbucket]
pop3_port = 54326
port = 54324
smtp_port = 54325
[storage]
file_size_limit = "50MiB"
[studio]
port = 54323
