export const whatsappEvents = [
  'auth_failure',
  'authenticated',
  'change_battery',
  'change_state',
  'disconnected',
  'group_join',
  'group_leave',
  'group_update',
  'media_uploaded',
  'message',
  'message_ack',
  'message_create',
  'message_revoke_everyone',
  'message_revoke_me',
  'message_reaction',
  'loading_screen',
  'qr',
  'call',
  'ready',
  'remote_session_saved',
] as const;
